# health check
curl --location --request GET 'localhost:8080/api/v1/health' --header 'Content-Type: application/json'

###

# getMetrics by <room_id>
curl --location --request GET 'localhost:8080/api/v1/getMetrics/<room_id>' --header 'Content-Type: application/json'